GharXpertWeb/Controllers/ServiceChargesController.cs
using AutoMapper;
using Gharxpert_Utility;
using GharXpertWeb.Models;
using GharXpertWeb.Models.Dto;
using GharXpertWeb.Models.VM;
using GharXpertWeb.Service;
using GharXpertWeb.Service.IService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;

namespace GharXpertWeb.Controllers
{
    public class ServiceChargesController : Controller
    {
        private readonly IWorkService _workService;
        private readonly IWorkTypeService _workTypeService;
        private readonly IServiceChargesService _serviceChargesService;
        private readonly IConstructionTypeService _constructionTypeService;
        private readonly IMapper _mapper;

        public ServiceChargesController(IServiceChargesService serviceChargesService, IWorkTypeService workTypeService, IWorkService workService,
            IConstructionTypeService constructionTypeService, IMapper mapper)
        {
            _workService = workService;
            _workTypeService = workTypeService;
            _mapper = mapper;
            _serviceChargesService = serviceChargesService;
            _constructionTypeService = constructionTypeService;
        }

        //public async Task<IActionResult> IndexServiceCharges()
        //{
        //    List<ServiceChargesDTO> list = new();
        //    var response = await _serviceChargesService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
        //    if (response != null && response.IsSuccess)
        //    {
        //        list = JsonConvert.DeserializeObject<List<ServiceChargesDTO>>(Convert.ToString(response.Result));
        //    }

        //    return View(list);
        //}

        public async Task<IActionResult> IndexServiceCharges()
        {
            List<ServiceChargesDTO> list = new();
            var response = await _serviceChargesService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<ServiceChargesDTO>>(Convert.ToString(response.Result));
            }

            return View(list);
        }

        public async Task<IActionResult> CreateServiceCharges()
        {
            ServiceChargesCreateVM serviceChargesVM = new();
            var response = await _workTypeService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                serviceChargesVM.WorkTypeList = JsonConvert.DeserializeObject<List<WorkTypeDTO>>
                    (Convert.ToString(response.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Work_Type,
                        Value = i.Id.ToString()
                    }); ;
            }

            var res = await _workService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (res != null && res.IsSuccess)
            {
                serviceChargesVM.WorkList = JsonConvert.DeserializeObject<List<WorkDTO>>
                    (Convert.ToString(res.Result)).Select(i => new SelectListItem
                    {
                        Text = i.WorkName,
                        Value = i.Id.ToString()
                    }); ;
            }

            var re = await _constructionTypeService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (re != null && res.IsSuccess)
            {
                serviceChargesVM.ConstructionTypeList = JsonConvert.DeserializeObject<List<ConstructionTypeDTO>>
                    (Convert.ToString(re.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Ctype,
                        Value = i.Cno.ToString()
                    }); ;
            }
            return View(serviceChargesVM);
        }

        //[Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateServiceCharges(ServiceChargesCreateVM model)
        {
            if (ModelState.IsValid)
            {
                var response = await _serviceChargesService.CreateAsync<APIResponse>(model.ServiceCharges, HttpContext.Session.GetString(SD.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexServiceCharges));
                }
                else
                {
                    if (response.ErrorMessages.Count > 0)
                    {
                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                    }
                }
            }

            var resp = await _workTypeService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (resp != null && resp.IsSuccess)
            {
                model.WorkTypeList = JsonConvert.DeserializeObject<List<WorkTypeDTO>>
                    (Convert.ToString(resp.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Work_Type,
                        Value = i.Id.ToString()
                    }); ;
            }

            var res = await _workService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (res != null && res.IsSuccess)
            {
                model.WorkList = JsonConvert.DeserializeObject<List<WorkDTO>>
                    (Convert.ToString(res.Result)).Select(i => new SelectListItem
                    {
                        Text = i.WorkName,
                        Value = i.Id.ToString()
                    }); ;
            }

            var re = await _constructionTypeService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (re != null && re.IsSuccess)
            {
                model.ConstructionTypeList = JsonConvert.DeserializeObject<List<ConstructionTypeDTO>>
                    (Convert.ToString(re.Result)).Select(i => new SelectListItem
                    {
                        Text = i.Ctype,
                        Value = i.Cno.ToString()
                    }); ;
            }

            return View(model);
        }

        public async Task<IActionResult> UpdateServiceCharges(int serviceChargesId)
        {
            ServiceChargesUpdateVM serviceChargesVM = new();
            var response = await _serviceChargesService.GetAsync<APIResponse>(serviceChargesId, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                ServiceChargesDTO model = JsonConvert.DeserializeObject<ServiceChargesDTO>(Convert.ToString(response.Result));
                serviceChargesVM.ServiceCharges = _mapper.Map<ServiceChargesUpdateDTO>(model);
            }
            if (response != null && response.IsSuccess)
            {


                response = await _workTypeService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    serviceChargesVM.WorkTypeList = JsonConvert.DeserializeObject<List<WorkTypeDTO>>
                        (Convert.ToString(response.Result)).Select(i => new SelectListItem
                        {
                            Text = i.Work_Type,
                            Value = i.Id.ToString()
                        });
                }

                response = await _workService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    serviceChargesVM.WorkList = JsonConvert.DeserializeObject<List<WorkDTO>>
                        (Convert.ToString(response.Result)).Select(i => new SelectListItem
                        {
                            Text = i.WorkName,
                            Value = i.Id.ToString()
                        });
                }

                response = await _constructionTypeService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    serviceChargesVM.ConstructionTypeList = JsonConvert.DeserializeObject<List<ConstructionTypeDTO>>
                        (Convert.ToString(response.Result)).Select(i => new SelectListItem
                        {
                            Text = i.Ctype,
                            Value = i.Cno.ToString()
                        });

                }
                return View(serviceChargesVM);
            }
            return NotFound();
        }

        //[Authorize(Roles = "admin")]

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateServiceCharges(ServiceChargesUpdateVM model)
        {
            if (ModelState.IsValid)
            {
                var response = await _serviceChargesService.UpdateAsync<APIResponse>(model.ServiceCharges, HttpContext.Session.GetString(SD.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexServiceCharges));
                }
                else
                {
                    if (response.ErrorMessages.Count > 0)
                    {
                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                    }
                }
            }
            var resp = await _workTypeService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (resp != null && resp.IsSuccess)
            {

GharXpertWeb/Views/ServiceCharges/CreateServiceCharges.cshtml
@model GharXpertWeb.Models.VM.ServiceChargesCreateVM

<form asp-action="CreateServiceCharges">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Create ServiceCharges</h1>
        <hr />

        <div class="row">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="ServiceCharges.Id" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="ServiceCharges.Id" class="form-control" />
                <span asp-validation-for="ServiceCharges.Id" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="ServiceCharges.WorkTypeId" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <select asp-for="ServiceCharges.WorkTypeId" class="form-select" asp-items="@Model.WorkTypeList">
                    <option disabled selecte>--Select WorkType--</option>
                </select>
                <span asp-validation-for="ServiceCharges.WorkTypeId" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="ServiceCharges.WorkId" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <select asp-for="ServiceCharges.WorkId" class="form-select" asp-items="@Model.WorkList">
                    <option disabled selecte>--Select Work--</option>
                </select>
                <span asp-validation-for="ServiceCharges.WorkId" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="ServiceCharges.ConstructionTypeId" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <select asp-for="ServiceCharges.ConstructionTypeId" class="form-select" asp-items="@Model.ConstructionTypeList">
                    <option disabled selecte>--Select ConstructionType--</option>
                </select>
                <span asp-validation-for="ServiceCharges.ConstructionTypeId" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="ServiceCharges.ServiceName" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="ServiceCharges.ServiceName" class="form-control" />
                <span asp-validation-for="ServiceCharges.ServiceName" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="ServiceCharges.Price" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="ServiceCharges.Price" class="form-control" />
                <span asp-validation-for="ServiceCharges.Price" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="ServiceCharges.Units" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="ServiceCharges.Units" class="form-control" />
                <span asp-validation-for="ServiceCharges.Units" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="ServiceCharges.UserId" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="ServiceCharges.UserId" class="form-control" />
                <span asp-validation-for="ServiceCharges.UserId" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexServiceCharges" asp-controller="ServiceCharges" class="btn-primary btn form-control">Back To List</a>
            </div>

            <div class="col-5">
                <input type="submit" value="Create" class="btn-success form-control" />
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

GharXpertWeb/Views/ServiceCharges/DeleteServiceCharges.cshtml
@model GharXpertWeb.Models.VM.ServiceChargesDeleteVM

<form asp-action="DeleteServiceCharges">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Delete ServiceCharges</h1>
        <hr />
        <input hidden asp-for="ServiceCharges.Id" />
        <div class="row">

            <div class="col-2">
                <label asp-for="ServiceCharges.Id" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="ServiceCharges.Id" disabled class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="ServiceCharges.WorkTypeId" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <select asp-for="ServiceCharges.WorkTypeId" disabled class="form-select" asp-items="@Model.WorkTypeList">
                    <option disabled selecte>--Select WorkType--</option>
                </select>
            </div>

            <div class="col-2">
                <label asp-for="ServiceCharges.WorkId" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <select asp-for="ServiceCharges.WorkId" disabled class="form-select" asp-items="@Model.WorkList">
                    <option disabled selecte>--Select Work--</option>
                </select>
            </div>

            <div class="col-2">
                <label asp-for="ServiceCharges.ConstructionTypeId" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <select asp-for="ServiceCharges.ConstructionTypeId" disabled class="form-select" asp-items="@Model.ConstructionTypeList">
                    <option disabled selecte>--Select ConstructionType--</option>
                </select>
            </div>

            <div class="col-2">
                <label asp-for="ServiceCharges.ServiceName" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="ServiceCharges.ServiceName" disabled class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="ServiceCharges.Price" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="ServiceCharges.Price" disabled class="form-check-label" />
            </div>

            <div class="col-2">
                <label asp-for="ServiceCharges.UserId" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="ServiceCharges.UserId" disabled class="form-control" />
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexServiceCharges" asp-controller="ServiceCharges" class="btn-primary btn form-control">Back To List</a>
            </div>

            <div class="col-5">
                <input type="submit" value="Delete" class="btn btn-danger form-control" />
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

GharXpertWeb/Views/ServiceCharges/IndexServiceCharges.cshtml
@model IEnumerable<GharXpertWeb.Models.Dto.ServiceChargesDTO>
<br />
<div class=" container p-4 border">
    <div class=" row pb-2">
        <div class="col">
            <h1 class="text-primary">ServiceCharges List</h1>
        </div>
        <div class="col text-end pt-1">
            <a asp-contoller="ServiceCharges" asp-action="CreateServiceCharges" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i> Create New ServiceCharges</a>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Service Name
                    </th>
                    <th>
                        Price
                    </th>
                    <th>
                        Work Type ID
                    </th>
                    <th>
                        Work ID
                    </th>
                    <th>
                        Construction Type ID
                    </th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.ServiceName</td>
                        <td>@item.Price</td>
                        <td>@item.WorkTypeId</td>
                        <td>@item.WorkId</td>
                        <td>@item.ConstructionTypeId</td>
                        <td>
                            <a asp-contoller="ServiceCharges" asp-action="UpdateServiceCharges" asp-route-serviceChargesId="@item.Id" class="btn btn-success"><i class="bi bi-pencil-square"></i> </a>
                            <a asp-contoller="ServiceCharges" asp-action="DeleteServiceCharges" asp-route-serviceChargesId="@item.Id" class="btn btn-danger"><i class="bi bi-trash-fill"></i> </a>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

GharXpertWeb/Views/ServiceCharges/UpdateServiceCharges.cshtml
@model GharXpertWeb.Models.VM.ServiceChargesUpdateVM

<form asp-action="UpdateServiceCharges">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Update ServiceCharges</h1>
        <hr />
        <input hidden asp-for="ServiceCharges.WorkTypeId" />
        <div class="row">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="ServiceCharges.Id" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="ServiceCharges.Id" class="form-control" />
                <span asp-validation-for="ServiceCharges.Id" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="ServiceCharges.WorkTypeId" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <select asp-for="ServiceCharges.WorkTypeId" class="form-select" asp-items="@Model.WorkTypeList">
                    <option disabled selecte>--Select WorkType--</option>
                </select>
                <span asp-validation-for="ServiceCharges.WorkTypeId" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="ServiceCharges.WorkId" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <select asp-for="ServiceCharges.WorkId" class="form-select" asp-items="@Model.WorkList">
                    <option disabled selecte>--Select Work--</option>
                </select>
                <span asp-validation-for="ServiceCharges.WorkId" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="ServiceCharges.ConstructionTypeId" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <select asp-for="ServiceCharges.ConstructionTypeId" class="form-select" asp-items="@Model.ConstructionTypeList">
                    <option disabled selecte>--Select ConstructionType--</option>
                </select>
                <span asp-validation-for="ServiceCharges.ConstructionTypeId" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="ServiceCharges.ServiceName" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="ServiceCharges.ServiceName" class="form-control" />
                <span asp-validation-for="ServiceCharges.ServiceName" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="ServiceCharges.Price" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="ServiceCharges.Price" class="form-check-label" />
                <span asp-validation-for="ServiceCharges.Price" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="ServiceCharges.UserId" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="ServiceCharges.UserId" class="form-control" />
                <span asp-validation-for="ServiceCharges.UserId" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexServiceCharges" asp-controller="ServiceCharges" class="btn-primary btn form-control">Back To List</a>
            </div>

            <div class="col-5">
                <input type="submit" value="Update" class="btn-success form-control" />
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}