GharXpertWeb/Controllers/ConstructionTypeController.cs
using AutoMapper;
using Gharxpert_Utility;
using GharXpertWeb.Models;
using GharXpertWeb.Models.Dto;
using GharXpertWeb.Service.IService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace GharXpertWeb.Controllers
{

    public class ConstructionTypeController : Controller
    {
        private readonly IConstructionTypeService _constructionTypeService;
        private readonly IMapper _mapper;
        public ConstructionTypeController(IConstructionTypeService constructionTypeService, IMapper mapper)
        {
            _constructionTypeService = constructionTypeService;
            _mapper = mapper;
        }
        public async Task<IActionResult> IndexConstructionType()
        {
            List<ConstructionTypeDTO> list = new();
            var response = await _constructionTypeService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<ConstructionTypeDTO>>(Convert.ToString(response.Result));
            }

            return View(list);
        }


        public async Task<IActionResult> CreateConstructionType()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateConstructionType(ConstructionTypeCreateDTO model)
        {
            if (ModelState.IsValid)
            {
                var response = await _constructionTypeService.CreateAsync<APIResponse>(model, HttpContext.Session.GetString(SD.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    TempData["Success"] = "ConstructionType created successfully";
                    return RedirectToAction(nameof(IndexConstructionType));
                }
            }
            TempData["error"] = "error encountered.";
            return View(model);
        }

        public async Task<IActionResult> UpdateConstructionType(int constructionTypeId)
        {
            var response = await _constructionTypeService.GetAsync<APIResponse>(constructionTypeId, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                ConstructionTypeDTO model = JsonConvert.DeserializeObject<ConstructionTypeDTO>(Convert.ToString(response.Result));
                return View(_mapper.Map<ConstructionTypeUpdateDTO>(model));
            }
            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateConstructionType(ConstructionTypeUpdateDTO model)
        {
            if (ModelState.IsValid)
            {
                TempData["Success"] = "ConstructionType updated successfully";
                var response = await _constructionTypeService.UpdateAsync<APIResponse>(model, HttpContext.Session.GetString(SD.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexConstructionType));
                }
            }
            TempData["error"] = "error encountered.";
            return View(model);
        }

        public async Task<IActionResult> DeleteConstructionType(int constructionTypeId)
        {
            var response = await _constructionTypeService.GetAsync<APIResponse>(constructionTypeId, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                ConstructionTypeDTO model = JsonConvert.DeserializeObject<ConstructionTypeDTO>(Convert.ToString(response.Result));
                return View(model);
            }
            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConstructionType(ConstructionTypeDTO model)
        {

            var response = await _constructionTypeService.DeleteAsync<APIResponse>(model.Cno, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                TempData["Success"] = "ConstructionType deleted successfully";
                return RedirectToAction(nameof(IndexConstructionType));
            }
            TempData["error"] = "error encountered.";
            return View(model);
        }
    }
}

GharXpertWeb/Views/ConstructionType/CreateConstructionType.cshtml
@model GharXpertWeb.Models.Dto.ConstructionTypeCreateDTO
<form asp-action="CreateConstructionType">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Create ConstructionType</h1>
        <hr />

        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="Cno" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="Cno" class="form-control" />
                <span asp-validation-for="Cno" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Ctype" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="Ctype" class="form-control" />
                <span asp-validation-for="Ctype" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexConstructionType" asp-controller="ConstructionType" class="btn-primary btn form-control">Back To List</a>
            </div>

            <div class="col-5">
                <input type="submit" value="Create" class="btn-success form-control" />
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

GharXpertWeb/Views/ConstructionType/DeleteConstructionType.cshtml
@model GharXpertWeb.Models.Dto.ConstructionTypeDTO
<form asp-action="DeleteConstructionType">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Delete ConstructionType</h1>
        <hr />

        <input hidden asp-for="Cno" />

        <div class="row">
            
            <div class="col-2">
                <label asp-for="Cno" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="Cno" disabled class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="Ctype" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="Ctype" disabled class="form-control" />
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexConstructionType" asp-controller="ConstructionType" class="btn-primary btn form-control">Back To List</a>
            </div>

            <div class="col-5">
                <input type="submit" value="Delete" class="btn btn-danger form-control" />
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

GharXpertWeb/Views/ConstructionType/IndexConstructionType.cshtml
@model IEnumerable<GharXpertWeb.Models.Dto.ConstructionTypeDTO>
<br />
<div class=" container p-4 border">
    <div class=" row pb-2">
        <div class="col">
            <h1 class="text-primary">ConstructionType List</h1>
        </div>
        <div class="col text-end pt-1">
            <a asp-contoller="ConstructionType" asp-action="CreateConstructionType" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i> Create New ConstructionType</a>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Cno
                    </th>
                    <th>
                        Construction Type
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Cno</td>
                        <td>@item.Ctype</td>
                        <td>
                            <a asp-contoller="ConstructionType" asp-action="UpdateConstructionType" asp-route-constructionTypeId="@item.Cno" class="btn btn-success"><i class="bi bi-pencil-square"></i> </a>
                            <a asp-contoller="ConstructionType" asp-action="DeleteConstructionType" asp-route-constructionTypeId="@item.Cno" class="btn btn-danger"><i class="bi bi-trash-fill"></i> </a>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

GharXpertWeb/Views/ConstructionType/UpdateConstructionType.cshtml
@model GharXpertWeb.Models.Dto.ConstructionTypeUpdateDTO
<form asp-action="UpdateConstructionType">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Update ConstructionType</h1>
        <hr />

        <input hidden asp-for="Cno" />

        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="Cno" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="Cno" class="form-control" />
                <span asp-validation-for="Cno" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="Ctype" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="Ctype" class="form-control" />
                <span asp-validation-for="Ctype" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexConstructionType" asp-controller="ConstructionType" class="btn-primary btn form-control">Back To List</a>
            </div>

            <div class="col-5">
                <input type="submit" value="Update" class="btn-success form-control" />
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}