GharXpertWeb/Controllers/WorkTypeController.cs
using AutoMapper;
using Gharxpert_Utility;
using GharXpertWeb.Models;
using GharXpertWeb.Models.Dto;
using GharXpertWeb.Models.VM;
using GharXpertWeb.Service;
using GharXpertWeb.Service.IService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;

namespace GharXpertWeb.Controllers
{
    public class WorkTypeController : Controller
    {

        private readonly IWorkTypeService _workTypeService;
        private readonly IWorkService _workService;
        private readonly IMapper _mapper;

        public WorkTypeController(IWorkTypeService workTypeService, IMapper mapper, IWorkService workService)
        {
            _workTypeService = workTypeService;
            _mapper = mapper;
            _workService = workService;
        }

        public async Task<IActionResult> IndexWorkType()
        {
            List<WorkTypeDTO> list = new();
            var response = await _workTypeService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<WorkTypeDTO>>(Convert.ToString(response.Result));
            }

            return View(list);
        }

        public async Task<IActionResult> CreateWorkType()
        {
            WorkTypeCreateVM workTypeVM = new();
            var response = await _workService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                workTypeVM.WorkList = JsonConvert.DeserializeObject<List<WorkDTO>>
                    (Convert.ToString(response.Result)).Select(i => new SelectListItem
                    {
                        Text = i.WorkName,
                        Value = i.Id.ToString()
                    }); ;
            }
            return View(workTypeVM);
        }

        //[Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateWorkType(WorkTypeCreateVM model)
        {
            if (ModelState.IsValid)
            {
                var response = await _workTypeService.CreateAsync<APIResponse>(model.WorkType, HttpContext.Session.GetString(SD.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexWorkType));
                }
                else
                {
                    if (response.ErrorMessages.Count > 0)
                    {
                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                    }
                }
            }

            var resp = await _workService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (resp != null && resp.IsSuccess)
            {
                model.WorkList = JsonConvert.DeserializeObject<List<WorkDTO>>
                    (Convert.ToString(resp.Result)).Select(i => new SelectListItem
                    {
                        Text = i.WorkName,
                        Value = i.Id.ToString()
                    }); ;
            }

            return View(model);
        }

        public async Task<IActionResult> UpdateWorkType(int workTypeId)
        {
            WorkTypeUpdateVM workTypeVM = new();
            var response = await _workTypeService.GetAsync<APIResponse>(workTypeId, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                WorkTypeDTO model = JsonConvert.DeserializeObject<WorkTypeDTO>(Convert.ToString(response.Result));
                workTypeVM.WorkType = _mapper.Map<WorkTypeUpdateDTO>(model);
            }

            response = await _workService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                workTypeVM.WorkList = JsonConvert.DeserializeObject<List<WorkDTO>>
                    (Convert.ToString(response.Result)).Select(i => new SelectListItem
                    {
                        Text = i.WorkName,
                        Value = i.Id.ToString()
                    });
                return View(workTypeVM);
            }
            return NotFound();
        }

        //[Authorize(Roles = "admin")]

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateWorkType (WorkTypeUpdateVM model)
        {
            if (ModelState.IsValid)
            {
                var response = await _workTypeService.UpdateAsync<APIResponse>(model.WorkType, HttpContext.Session.GetString(SD.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexWorkType));
                }
                else
                {
                    if (response.ErrorMessages.Count > 0)
                    {
                        ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                    }
                }
            }
            var resp = await _workService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (resp != null && resp.IsSuccess)
            {
                model.WorkList = JsonConvert.DeserializeObject<List<WorkDTO>>
                    (Convert.ToString(resp.Result)).Select(i => new SelectListItem
                    {
                        Text = i.WorkName,
                        Value = i.Id.ToString()
                    });
            }
            return View(model);
        }

        public async Task<IActionResult> DeleteWorkType(int workTypeId)
        {
            WorkTypeDeleteVM workTypeVM = new();
            var response = await _workTypeService.GetAsync<APIResponse>(workTypeId, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                WorkTypeDTO model = JsonConvert.DeserializeObject<WorkTypeDTO>(Convert.ToString(response.Result));
                workTypeVM.WorkType = model;
            }

            response = await _workService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                workTypeVM.WorkList = JsonConvert.DeserializeObject<List<WorkDTO>>
                    (Convert.ToString(response.Result)).Select(i => new SelectListItem
                    {
                        Text = i.WorkName,
                        Value = i.Id.ToString()
                    });
                return View(workTypeVM);
            }
            return NotFound();
        }

        //[Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteWorkType(WorkTypeDeleteVM model)
        {

            var response = await _workTypeService.DeleteAsync<APIResponse>(model.WorkType.Id, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                return RedirectToAction(nameof(IndexWorkType));
            }

            return View(model);
        }

    }
}

GharXpertWeb/Views/WorkType/CreateWorkType.cshtml
@model GharXpertWeb.Models.VM.WorkTypeCreateVM

<form asp-action="CreateWorkType">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Create WorkType</h1>
        <hr />

        <div class="row">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="WorkType.Id" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="WorkType.Id" class="form-control" />
                <span asp-validation-for="WorkType.Id" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="WorkType.WorkID" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <select asp-for="WorkType.WorkID" class="form-select" asp-items="@Model.WorkList">
                    <option disabled selecte>--Select Work--</option>
                </select>
                <span asp-validation-for="WorkType.WorkID" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="WorkType.Work_Type" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="WorkType.Work_Type" class="form-control" />
                <span asp-validation-for="WorkType.Work_Type" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="WorkType.WorkDesc" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <textarea asp-for="WorkType.WorkDesc" class="form-control" rows="5"></textarea>
                <span asp-validation-for="WorkType.WorkDesc" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="WorkType.WorkImage" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="WorkType.WorkImage" class="form-control" />
                <span asp-validation-for="WorkType.WorkImage" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="WorkType.IsActive" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="WorkType.IsActive" class="form-check-label" />
                <span asp-validation-for="WorkType.IsActive" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexWorkType" asp-controller="WorkType" class="btn-primary btn form-control">Back To List</a>
            </div>

            <div class="col-5">
                <input type="submit" value="Create" class="btn-success form-control" />
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

GharXpertWeb/Views/WorkType/DeleteWorkType.cshtml
@model GharXpertWeb.Models.VM.WorkTypeDeleteVM

<form asp-action="DeleteWorkType">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Delete Work Type</h1>
        <hr />
        <input hidden asp-for="WorkType.Id" />
        <div class="row">

            <div class="col-2">
                <label asp-for="WorkType.Id" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="WorkType.Id" disabled class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="WorkType.WorkID" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <select asp-for="WorkType.WorkID" disabled class="form-select" asp-items="@Model.WorkList">
                    <option disabled selecte>--Select Work--</option>
                </select>
            </div>

            <div class="col-2">
                <label asp-for="WorkType.Work_Type" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="WorkType.Work_Type" disabled class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="WorkType.WorkDesc" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <textarea asp-for="WorkType.WorkDesc" readonly class="form-control" rows="5"></textarea>
            </div>

            <div class="col-2">
                <label asp-for="WorkType.WorkImage" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="WorkType.WorkImage" disabled class="form-control" />
            </div>

            <div class="col-2">
                <label asp-for="WorkType.IsActive" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="WorkType.IsActive" disabled class="form-check-label" />
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexWorkType" asp-controller="WorkType" class="btn-primary btn form-control">Back To List</a>
            </div>

            <div class="col-5">
                <input type="submit" value="Delete" class="btn btn-danger form-control" />
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

GharXpertWeb/Views/WorkType/IndexWorkType.cshtml
@model IEnumerable<GharXpertWeb.Models.Dto.WorkTypeDTO>
<br />
<div class=" container p-4 border">
    <div class=" row pb-2">
        <div class="col">
            <h1 class="text-primary">WorkType List</h1>
        </div>
        <div class="col text-end pt-1">
            <a asp-contoller="Work" asp-action="CreateWorkType" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i> Create New WorkType</a>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Work Type
                    </th>
                    <th>
                        Work Desc
                    </th>
                    <th>
                        Work Image
                    </th>
                    <th>
                        Work IsActive
                    </th>
                    <th>
                        Work ID
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Work_Type</td>
                        <td>@item.WorkDesc</td>
                        <td>@item.WorkImage</td>
                        <td>@item.IsActive</td>
                        <td>@item.WorkID</td>
                        <td>
                            <a asp-contoller="Work" asp-action="UpdateWorkType" asp-route-workTypeId="@item.Id" class="btn btn-success"><i class="bi bi-pencil-square"></i> </a>
                            <a asp-contoller="Work" asp-action="DeleteWorkType" asp-route-workTypeId="@item.Id" class="btn btn-danger"><i class="bi bi-trash-fill"></i> </a>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

GharXpertWeb/Views/WorkType/UpdateWorkType.cshtml
@model GharXpertWeb.Models.VM.WorkTypeUpdateVM

<form asp-action="UpdateWorkType">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Update Work Type</h1>
        <hr />
        <input hidden asp-for="WorkType.WorkID" />
        <div class="row">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="WorkType.Id" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="WorkType.Id" class="form-control" />
                <span asp-validation-for="WorkType.Id" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="WorkType.WorkID" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <select asp-for="WorkType.WorkID" class="form-select" asp-items="@Model.WorkList">
                    <option disabled selecte>--Select Work--</option>
                </select>
                <span asp-validation-for="WorkType.WorkID" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="WorkType.Work_Type" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="WorkType.Work_Type" class="form-control" />
                <span asp-validation-for="WorkType.Work_Type" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="WorkType.WorkDesc" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <textarea asp-for="WorkType.WorkDesc" class="form-control" rows="5"></textarea>
                <span asp-validation-for="WorkType.WorkDesc" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="WorkType.WorkImage" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="WorkType.WorkImage" class="form-control" />
                <span asp-validation-for="WorkType.WorkImage" class="text-danger"></span>
            </div>

            <div class="col-2">
                <label asp-for="WorkType.IsActive" class="control-label pt-2" style="font-size:20px;"></label>
            </div>

            <div class="col-10 pb-3">
                <input asp-for="WorkType.IsActive" class="form-check-label" />
                <span asp-validation-for="WorkType.IsActive" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">
                <a asp-action="IndexWorkType" asp-controller="WorkType" class="btn-primary btn form-control">Back To List</a>
            </div>

            <div class="col-5">
                <input type="submit" value="Update" class="btn-success form-control" />
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}